apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    app: minio
  type: ClusterIP
  ports:
    - name: minio
      protocol: TCP
      port: 9090
      targetPort: 9090
